### ISSUE TITLE
Exception inside async is not thrown

### ISSUE THREAD

**Issue by triwahyuu** [okyfirmansyah/libasyik#13]
I have an exception that is thrown inside `as->async`, but is not thrown in the main thread so the code looks like it is stuck in the function that is throwing the exception.

I'm using libasyik v0.8.1

**Comment by okyfirmansyah** [comment]
Hi, @triwahyuu can you give a minimal, reproducable example for this issue?

**Comment by triwahyuu** [comment]
I found that my code is throwing error in opencv. You can reproduce using:

`main.cpp`
```
#include <libasyik/service.hpp>
#include <opencv2/imgproc.hpp>


void failed_resize() {
    cv::Mat img;
    cv::resize(img, img, cv::Size(128, 128));
}

int main(int argc, char **argv)
{
    failed_resize();     // will fail here

    auto as = asyik::make_service();
    as->async([]() {
        failed_resize();
    });
    return 0;
}
```

`CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.14)
project(test_libasyik)
set(CMAKE_CXX_STANDARD 17)

add_executable(${PROJECT_NAME} main.cpp)

find_package(libasyik)
target_include_directories(${PROJECT_NAME} PUBLIC ${libasyik_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} libasyik)

find_package(OpenCV REQUIRED)
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS})

find_package(Boost COMPONENTS context fiber date_time REQUIRED)
target_include_directories(${PROJECT_NAME} PUBLIC ${Boost_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} Boost::fiber Boost::context Boost::date_time)

find_package(SOCI REQUIRED)
target_include_directories(${PROJECT_NAME} PUBLIC /usr/include/postgresql)
target_include_directories(${PROJECT_NAME} PUBLIC /usr/local/include/soci)
target_include_directories(${PROJECT_NAME} PUBLIC /usr/local/include/soci/postgresql)
target_include_directories(${PROJECT_NAME} PUBLIC /usr/local/include/soci/sqlite3)
target_link_libraries(${PROJECT_NAME} SOCI::soci_core SOCI::soci_postgresql SOCI::soci_sqlite3)

find_package(Threads REQUIRED)
target_link_libraries(${PROJECT_NAME} Threads::Threads)

find_package(OpenSSL REQUIRED)
target_link_libraries(${PROJECT_NAME} OpenSSL::SSL)
```

**Comment by triwahyuu** [comment]
turns out it also happened when using any `std::exception` exception.

```
#include <libasyik/service.hpp>
#include <stdexcept>


void throw_error()
{
    throw std::runtime_error("this should fail!!\n");
}

int main(int argc, char **argv)
{
    // throw_error();   // will fail here

    auto as = asyik::make_service();
    as->async([]() {
        throw_error();
    });

    return 0;
}
```

**Comment by okyfirmansyah** [comment]
Hi @triwahyuu, this is **expected** and **by-design**.

You can see that `.exec()` and `.async()` are actually returning `fibers::future`. So if you want to forward the routine's outcome, be it **return value** or **exception**, you can use `.get()`:

```c++
int main(int argc, char **argv)
{
    // throw_error();   // will fail here

    auto as = asyik::make_service();
    as->async([]() {
        throw_error();

        return true;
    }).get();  // exception will be forwarded here (instead of return true)

    return 0;
}
```
You can also store the `future` for later evaluation. Any result or exception will be returned when `.get()` is called:
```c++
int main(int argc, char **argv)
{
    // throw_error();   // will fail here

    auto as = asyik::make_service();
    auto result = as->async([]() {
        throw_error();

        return true;
    });

    // some other part of code...
    auto result_value = result.get(); // exception will be thrown here

    return 0;
}
```

Of course the difference between this and your example is the `.get()` will actually **block execution** until the future/promise is fulfilled.

Now what happens when you don't follow up the result by `.get()`? 
Well since the `.exec()` and `.async()` are both designed to be executed independently relative to the calling thread/fiber, there is no proper, natural way to get the outcomes if you don't store the `future` and explicitly call `.get()`, so the exception will be swallowed.

**Comment by okyfirmansyah** [comment]
If exception in the routine is not acceptable by design and should initiate global assertion/exception(it's not recoverable), you can add `noexcept` spec to the lambda routine: https://stackoverflow.com/questions/16571125/using-noexcept-as-a-lambda-modifier-or-parameter-constraint
